sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - ./node_modules

notifications:
  email: false

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
